### ISSUE TITLE
Intallation issues

### ISSUE THREAD

**Issue by mikeCalvir** [bushbaby/diawi-uploader#1]
Hi,

I'd like to use this tool for uploading, and I apologise if this is a trivial error but I'm not at all familiar with Composer. I got this far with installation:

```
Mike-MB-Pro:diawi-uploader-master mike$ php composer.phar g require bushbaby/diawi-uploader
Changed current directory to /Users/mike/.composer
Using version ^0.1.2 for bushbaby/diawi-uploader
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bushbaby/diawi-uploader ^0.1.2 -> satisfiable by bushbaby/diawi-uploader[0.1.2].
    - bushbaby/diawi-uploader 0.1.2 requires roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master] but these conflict with your requirements or minimum-stability.


Installation failed, deleting ./composer.json.
```

And I've no idea why that failed, or what to try. The config file seems fine afaict, and I don't know what criteria it is using for rejecting the "roave" security package there. 

Any help or tips or pointers on how to get further with this would be appreciated - thanks in advance!
Mike

**Comment by basz** [comment]
add

```
"minimum-stability" : "dev",
"prefer-stable": true,
```
to 
`~/.composer/composer.json`

and try again.

i think that will solve it

**Comment by mikeCalvir** [comment]
Thanks basz!

Ok the composer file didn't exist there, so I copied it there from the diawi-uploader-master folder and updated with your added keys, then ran again, and it gets further now:

```
Mike-MB-Pro:diawi-uploader-master mike$ php composer.phar g require bushbaby/diawi-uploader
Changed current directory to /Users/mike/.composer
Using version ^0.1.2 for bushbaby/diawi-uploader
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bushbaby/diawi-uploader No version set (parsed as 1.0.0) is satisfiable by bushbaby/diawi-uploader[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

It tells me it modifies the config file but because it reverts I don't know what it does or why. 
Thanks for your help, I think we're getting closer :)

**Comment by basz** [comment]
I'm not sure coping just any composer.json file won't be problematic. I would suggest you delete and run `composer global init`. That creates such a file (you'll only need to set 'minimum-stability' to 'dev' which can be done with the init program...


```
rattletrap:~ bas$ mv ~/.composer/ ~/composer
rattletrap:~ bas$ composer global init
Changed current directory to /Users/bas/.composer

                                            
  Welcome to the Composer config generator  
                                            


This command will guide you through creating your composer.json config.

Package name (<vendor>/<name>) [bas/.composer]: 
Description []: 
Author [Bas Kamer <bas@xxxx>, n to skip]: n
Minimum Stability []: dev
Package Type (e.g. library, project, metapackage, composer-plugin) []: 
License []: 

Define your dependencies.

Would you like to define your dependencies (require) interactively [yes]? n
Would you like to define your dev dependencies (require-dev) interactively [yes]? n

{
    "name": "bas/.composer",
    "minimum-stability": "dev",
    "require": {}
}

Do you confirm generation [yes]? yes
rattletrap:~ bas$ composer global require bushbaby/diawi-uploader
Changed current directory to /Users/bas/.composer
Using version dev-master for bushbaby/diawi-uploader
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 14 installs, 0 updates, 0 removals
  - Installing psr/http-message (dev-master f6561bf): Cloning f6561bf28d from cache
  - Installing guzzlehttp/psr7 (dev-master f5b8a85): Cloning f5b8a8512e from cache
  - Installing guzzlehttp/promises (dev-master 73815f3): Cloning 73815f322d from cache
  - Installing guzzlehttp/guzzle (dev-master b517bd9): Cloning b517bd912a from cache
  - Installing psr/log (dev-master 4ebe3a8): Cloning 4ebe3a8bf7 from cache
  - Installing symfony/debug (dev-master a40c94b): Cloning a40c94b3ec from cache
  - Installing symfony/polyfill-mbstring (dev-master e79d363): Cloning e79d363049 from cache
  - Installing symfony/console (dev-master 386c1d9): Cloning 386c1d9d24 from cache
  - Installing psr/container (dev-master b7ce3b1): Cloning b7ce3b1764 from cache
  - Installing container-interop/container-interop (1.2.0): Downloading (100%)         
  - Installing zendframework/zend-stdlib (dev-develop 16818ed): Cloning 16818ed8ee from cache
  - Installing zendframework/zend-servicemanager (dev-develop d591ee5): Cloning d591ee53a2 from cache
  - Installing bushbaby/diawi-uploader (dev-master d25e6b0): Cloning d25e6b0d7c from cache
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/process ()
symfony/console suggests installing symfony/filesystem ()
zendframework/zend-servicemanager suggests installing ocramius/proxy-manager (ProxyManager 1.* to handle lazy initialization of services)
Writing lock file
Generating autoload files
```

**Comment by basz** [comment]
any luck here

**Comment by mikeCalvir** [comment]
Hey sorry I still want to do this, but every time I get back to it something else higher priority comes along! (Last time was this afternoon!).

Some quick notes: 
a. I didn't copy any old config, I took the one from the project, but maybe I'm wrong in thinking that was a good idea :)
b. I can't run:
 composer <args>
Because composer isn't known, I have to run it like:
 php composer.phar <args>
(I mention this as it might mean I don't have composer properly installed or something, or maybe I just need an alias for it?)

I still hope to get back to this and have it setup soon, it would have been nice today as I made multiple new releases and had to do them manually. 

Thanks for your help here, hopefully next session will crack it :)

**Comment by basz** [comment]
Hi Mike,

thats sounds familiar… Always hard to find time for the side projects

it should not be a problem composer vs composer.phar vs php composer.phar it depend on how you installed it. I tend to install it on my system and place it in my $PATH so i can run it from anywhere. But the .phar is also good. If you make it executable (chmod +x composer.phar) you can run it without the preceding php.

what does `php -v` tell you?
what does `php composer.phar` tell you?

to update to the latest composer version simply run it with the selfupdate flag `php composer.phar selfupdate`

not sure you know all these details, they are not that important...

luck

**Comment by mikeCalvir** [comment]
Ok so I followed the instructions above and it seems better, now I get:

Mike-MB-Pro:~ mike$ /Users/mike/WorkArea/dev/diawi-uploader-master/bin/diawi-uploader configure 

Fatal error: Class 'Zend\Stdlib\Glob' not found in /Users/mike/WorkArea/dev/diawi-uploader-master/config/config.php on line 27
Mike-MB-Pro:~ mike$ php -v
PHP 5.6.30 (cli) (built: Feb  7 2017 16:06:52) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
Mike-MB-Pro:~ mike$ php /Users/mike/WorkArea/dev/diawi-uploader-master/composer.phar
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.4.1 2017-03-10 09:29:45

Apologies, this looks like it's probably path or setup related and probably very simple, but you might solve this in seconds compared to my hours! :)

**Comment by basz** [comment]
No my bad, a missing dependency on zend-stdlib

I have release a new version

run to update

`composer.phar global update bushbaby/diawi-uploader`

**Comment by mikeCalvir** [comment]
Mike-MB-Pro:~ mike$ php /Users/mike/WorkArea/dev/diawi-uploader-master/composer.phar global update bushbaby/diawi-uploader
Changed current directory to /Users/mike/.composer
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating bushbaby/diawi-uploader dev-master (d25e6b0 => c184171):  Checking out c184171eba
Writing lock file
Generating autoload files
Mike-MB-Pro:~ mike$ /Users/mike/WorkArea/dev/diawi-uploader-master/bin/diawi-uploader configure 

Fatal error: Class 'Zend\Stdlib\Glob' not found in /Users/mike/WorkArea/dev/diawi-uploader-master/config/config.php on line 27
Mike-MB-Pro:~ mike$

**Comment by basz** [comment]
you’re mixing a globally installed version with a version installed at /Users/mike/WorkArea/dev/.

with the global flag packages are installed to ' /Users/mike/.composer/vendor’ otherwise to the directory your running composer from.

and as such you are trying to execute `/Users/mike/.composer/vendor/bin/diawi-uploader`

to confirm /Users/mike/.composer/vendor/bin is on your $PATH this command should tell you `which diawi-uploader`


I have added the following to ~/.bash_profile to make that path available. (might need to reopen the Terminal window)

export PATH=~/.composer/vendor/bin:$PATH

**Comment by mikeCalvir** [comment]
Ok I added that export to the bash profile, and then:

Mike-MB-Pro:~ mike$ diawi-uploader

Warning: Unsupported declare 'strict_types' in /Users/mike/.composer/vendor/bushbaby/diawi-uploader/src/App/Command/ConfigureCommand.php on line 3

Warning: Unsupported declare 'strict_types' in /Users/mike/.composer/vendor/bushbaby/diawi-uploader/src/App/Command/Container/UploadCommandFactory.php on line 3

Warning: Unsupported declare 'strict_types' in /Users/mike/.composer/vendor/bushbaby/diawi-uploader/src/App/Command/UploadCommand.php on line 3

Parse error: parse error in /Users/mike/.composer/vendor/bushbaby/diawi-uploader/src/App/Command/UploadCommand.php on line 90
Mike-MB-Pro:~ mike$

**Comment by basz** [comment]
Which php version are you using?

**Comment by mikeCalvir** [comment]
As listed above too :)

Mike-MB-Pro:~ mike$ php -v
PHP 5.6.30 (cli) (built: Feb  7 2017 16:06:52) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
Mike-MB-Pro:~ mike$

**Comment by basz** [comment]
Ha Mike, sorry i missed you where using that version of php.

The Error is due to a php7 construct. (I dont use 56 anymore)

But,... I did some simple update and it should be supported now. So another `composer.phar global update bushbaby/diawi-uploader` :-)

**Comment by mikeCalvir** [comment]
Thanks Bas. Maybe I should upgrade PHP? I never use it, its just whatever was installed with MacOS 10.12
But okay this seems to be working now, nice! 👍 
Thanks for all the help getting this going, and hopefully this thread helps someone else in future :)

**Comment by basz** [comment]
no problem, glad it is useful to someone else
